[package]
name = "carbon-lib"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "..."
repository = "https://github.com/nyar-lang/Notedown-rs"
readme = "README.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
syntect = "3.2"
lazy_static = "1.4.0"
carbon-dump = "1.1.0"

